import React, { useState } from 'react';
import { Copy, Check, Send, Sparkles } from 'lucide-react';

const PRGenerator = ({ lang = 'ja' }) => {
    const [formData, setFormData] = useState({
        type: 'nation',
        name: '',
        leader: '',
        capital: '',
        coords: '',
        concept: '',
        description: '',
        discord: '',
    });

    const [copied, setCopied] = useState(false);

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const generateMarkdown = () => {
        if (formData.type === 'nation') {
            return `### ${formData.name}
- **主権者**: ${formData.leader}
- **首都**: ${formData.capital}
- **特徴**: ${formData.concept}
- **詳細**: ${formData.description}
- **参加方法**: ${formData.discord}`;
        } else {
            return `### ${formData.name}
- **町長**: ${formData.leader}
- **所属国家**: ${formData.capital || '無所属'}
- **座標**: ${formData.coords}
- **紹介**: ${formData.description}
- **コンセプト**: ${formData.concept}`;
        }
    };

    const generateDiscord = () => {
        const emoji = formData.type === 'nation' ? '🌍' : '🏘️';
        return `${emoji} **【${formData.type === 'nation' ? '国家宣伝' : '町宣伝'}】 ${formData.name}** ${emoji}
━━━━━━━━━━━━━━━━━━━━━━━━
👤 **${formData.type === 'nation' ? '主権者' : '町長'}**: ${formData.leader}
${formData.type === 'nation' ? `🏛️ **首都**: ${formData.capital}` : `📍 **座標**: ${formData.coords}`}
✨ **コンセプト**: ${formData.concept}
📝 **紹介**: ${formData.description}
🔗 **連絡先**: ${formData.discord}
━━━━━━━━━━━━━━━━━━━━━━━━
#MARV #マインクラフト #建国鯖`;
    };

    const submitToGithub = () => {
        const title = encodeURIComponent(`[宣伝掲載申請] ${formData.name}`);
        const body = encodeURIComponent(`## 宣伝掲載申請 (Wiki Promotion Request)

以下の内容をWikiに掲載してください：

\`\`\`markdown
${generateMarkdown()}
\`\`\`

---
*Generated by MarvWiki PR Generator*`);

        const repoUrl = "https://github.com/Earth-Router/Marvwiki/issues/new";
        window.open(`${repoUrl}?title=${title}&body=${body}`, '_blank');
    };

    const submitToDiscord = async () => {
        // Use environment variable for the webhook URL
        const WEBHOOK_URL = import.meta.env.VITE_DISCORD_WEBHOOK_URL;

        if (!WEBHOOK_URL || WEBHOOK_URL.includes('YOUR_WEBHOOK_ID')) {
            alert(lang === 'ja' ? 'Webhook URLが設定されていません。.envファイルを確認してください。' : 'Webhook URL is not configured. Please check your .env file.');
            return;
        }

        const embed = {
            title: formData.type === 'nation' ? '🌍 新規国家掲載申請' : '🏘️ 新規町掲載申請',
            color: formData.type === 'nation' ? 0x3366cc : 0x2da44e,
            fields: [
                { name: '名称', value: formData.name, inline: true },
                { name: '代表者', value: formData.leader, inline: true },
                { name: formData.type === 'nation' ? '首都' : '所属国', value: formData.capital || 'N/A', inline: true },
                { name: '座標/連絡先', value: formData.coords || formData.discord || 'N/A' },
                { name: 'コンセプト', value: formData.concept },
                { name: '詳細', value: formData.description }
            ],
            footer: { text: 'Submitted via MarvWiki PR Generator' }
        };

        try {
            const response = await fetch(WEBHOOK_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ embeds: [embed] })
            });

            if (response.ok) {
                alert(lang === 'ja' ? 'Discordに送信しました！' : 'Sent to Discord!');
            } else {
                throw new Error('Failed to send');
            }
        } catch (err) {
            console.error(err);
            alert(lang === 'ja' ? '送信に失敗しました。Webhookの設定を確認してください。' : 'Failed to send. Please check Webhook settings.');
        }
    };

    const copyToClipboard = (text) => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const t = {
        ja: {
            title: '簡単PRジェネレーター',
            subtitle: '必要事項を入力するだけで、Wiki用とDiscord用の宣伝文を自動生成します。',
            type: '種類',
            nation: '国家',
            town: '町',
            name: '名称',
            leader: '代表者名',
            capital: '所属国 / 首都',
            coords: '座標 (x, z)',
            concept: 'コンセプト・特徴',
            description: '詳細説明',
            discord: 'Discord / 連絡先',
            preview: 'プレビュー',
            copyWiki: 'Wiki用コピー',
            copyDiscord: 'Discord用コピー',
            submitGithub: 'Wikiに掲載申請する (GitHub)',
            copied: 'コピーしました！'
        },
        en: {
            title: 'Quick PR Generator',
            subtitle: 'Fill in the details to generate promotion text for Wiki and Discord automatically.',
            type: 'Type',
            nation: 'Nation',
            town: 'Town',
            name: 'Name',
            leader: 'Leader',
            capital: 'Nation / Capital',
            coords: 'Coordinates (x, z)',
            concept: 'Concept / Features',
            description: 'Description',
            discord: 'Discord / Contact',
            preview: 'Preview',
            copyWiki: 'Copy for Wiki',
            copyDiscord: 'Copy for Discord',
            submitGithub: 'Submit to Wiki (GitHub)',
            copied: 'Copied!'
        }
    }[lang];

    return (
        <div className="pr-generator">
            <div className="generator-header">
                <h2><Sparkles size={24} style={{ color: '#3366cc', marginRight: '10px' }} />{t.title}</h2>
                <p>{t.subtitle}</p>
            </div>

            <div className="generator-grid">
                <div className="generator-form">
                    <div className="form-group">
                        <label>{t.type}</label>
                        <div className="radio-group">
                            <button
                                className={formData.type === 'nation' ? 'active' : ''}
                                onClick={() => setFormData(prev => ({ ...prev, type: 'nation' }))}
                            >{t.nation}</button>
                            <button
                                className={formData.type === 'town' ? 'active' : ''}
                                onClick={() => setFormData(prev => ({ ...prev, type: 'town' }))}
                            >{t.town}</button>
                        </div>
                    </div>

                    <div className="form-group">
                        <label>{t.name}</label>
                        <input name="name" value={formData.name} onChange={handleInputChange} placeholder={formData.type === 'nation' ? '例: マルヴ帝国' : '例: スポンジ町'} />
                    </div>

                    <div className="form-group">
                        <label>{t.leader}</label>
                        <input name="leader" value={formData.leader} onChange={handleInputChange} placeholder="Minecraft ID" />
                    </div>

                    <div className="form-group">
                        <label>{formData.type === 'nation' ? t.capital.split(' / ')[1] : t.capital.split(' / ')[0]}</label>
                        <input
                            name="capital"
                            value={formData.capital}
                            onChange={handleInputChange}
                            placeholder={formData.type === 'nation' ? '例: 本拠地の名前' : '例: 所属している国'}
                        />
                    </div>

                    {formData.type === 'town' && (
                        <div className="form-group">
                            <label>{t.coords}</label>
                            <input name="coords" value={formData.coords} onChange={handleInputChange} placeholder="例: 1000, -2000" />
                        </div>
                    )}

                    <div className="form-group">
                        <label>{t.concept}</label>
                        <input name="concept" value={formData.concept} onChange={handleInputChange} placeholder="例: 建築重視 / 初心者歓迎" />
                    </div>

                    <div className="form-group">
                        <label>{t.description}</label>
                        <textarea name="description" value={formData.description} onChange={handleInputChange} rows="4" placeholder="あなたの国や町の魅力を自由に書いてください。" />
                    </div>

                    <div className="form-group">
                        <label>{t.discord}</label>
                        <input name="discord" value={formData.discord} onChange={handleInputChange} placeholder="Discordの招待リンクなど" />
                    </div>
                </div>

                <div className="generator-preview">
                    <h3>{t.preview}</h3>

                    <div className="preview-box">
                        <div className="preview-label">Wiki (Markdown)</div>
                        <pre>{generateMarkdown()}</pre>
                        <div style={{ display: 'flex', gap: '10px' }}>
                            <button className="copy-btn" onClick={() => copyToClipboard(generateMarkdown())}>
                                {copied ? <Check size={14} /> : <Copy size={14} />} {t.copyWiki}
                            </button>
                            <button className="submit-btn" onClick={submitToGithub}>
                                <Github size={14} /> {t.submitGithub}
                            </button>
                            <button className="discord-submit-btn" onClick={submitToDiscord}>
                                <MessageCircle size={14} /> {lang === 'ja' ? 'Discordに直接送る' : 'Submit to Discord'}
                            </button>
                        </div>
                    </div>

                    <div className="preview-box">
                        <div className="preview-label">Discord (Formatted)</div>
                        <pre>{generateDiscord()}</pre>
                        <button className="copy-btn" onClick={() => copyToClipboard(generateDiscord())}>
                            {copied ? <Check size={14} /> : <Copy size={14} />} {t.copyDiscord}
                        </button>
                    </div>

                    <div className="hint-box">
                        <Send size={16} />
                        <p>{lang === 'ja' ? '生成した文章をWiki編集者に送るか、Discordの国街宣伝チャンネルに貼り付けてください！' : 'Send the generated text to a Wiki editor or paste it into the Discord channel!'}</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PRGenerator;
